### ISSUE TITLE
Issue on page /content/03/04f-betterplots.html

### ISSUE THREAD

**Issue by Brooks377** [LeDataSciFi/ledatascifi-2023#7]
State-by-industry leverage scatterplot is out of order in last 2 fyears.

**Comment by donbowen** [comment]
@donbowen (or someone?) fix this someday

**Comment by donbowen** [comment]
@Brooks377 Fixed: https://ledatascifi.github.io/ledatascifi-2023/content/03/04f3-interactive_figs.html
